#!/bin/bash
# ####################################################################
# script: buildpilomar_bookworm64
# Save as UNIX file.
# 11.Feb.2024 / Rasbian bookworm 64bit only
# ####################################################################

export pilomarhome='/home/pi/pilomar'
echo home directory is: $pilomarhome
export pilomarlog='/home/pi/pilomar/log/buildpilomar_bookworm64.log'
echo build logfile is: $pilomarlog

# list current packages and versions.
echo Initial packages installed>>$pilomarlog
echo - dpkg list:----------------------------------------------
dpkg-query -l>>$pilomarlog
echo - pip3 list:----------------------------------------------
pip3 list>>$pilomarlog
echo - apt list:-----------------------------------------------
apt list --installed>>$pilomarlog
echo ----------------------------------------------------------

# Log start of the script (AFTER checking that the target directory exists)
sudo chmod 777 $pilomarhome/log
echo $(date) buildpilomar script start >>$pilomarlog

echo
echo -e "==========================================================="
echo -e "\E[36;40mGeneral update...\E[0m"
echo $(date) General update >>$pilomarlog
# Update the application package directory.
sudo apt-get update -y
# Upgrade everything that's currently installed.
sudo apt-get upgrade -y

echo
echo -e "==========================================================="
echo -e "\E[36;40mSupport for skyfield...\E[0m"
echo $(date) skyfield - YES >>$pilomarlog
sudo apt install python3-skyfield

echo
echo -e "==========================================================="
echo -e "\E[36;40mSupport for opencv...\E[0m"
echo $(date) opencv - YES >>$pilomarlog
sudo apt install python3-opencv

echo
echo -e "==========================================================="
echo -e "\E[36;40mSupport for astroalign...\E[0m"
echo $(date) astroalign - YES >>$pilomarlog
sudo apt install python3-astroalign

echo
echo -e "==========================================================="
echo -e "\E[36;40mSupport for pandas...\E[0m"
echo $(date) pandas - YES >>$pilomarlog
sudo apt install python3-pandas


echo
echo Cleanup apt-get space. 
sudo apt autoremove
sudo apt-get clean

echo Final packages installed>>$pilomarlog
echo - dpkg list:----------------------------------------------
dpkg-query -l>>$pilomarlog
echo - pip3 list:----------------------------------------------
pip3 list>>$pilomarlog
echo - apt list:-----------------------------------------------
apt list --installed>>$pilomarlog
echo ----------------------------------------------------------

echo $(date) buildpilomar script end >>$pilomarlog

echo
echo -e "***********************************************************************************************************************"
echo -e "For PILOMAR you must also enable VNC, CAMERA, SSH and SERIAL PORT (but disable console to serial port) via raspi-config"
echo -e "***********************************************************************************************************************"

echo -e "\E[32;40m------------------------------\E[0m"
echo -e "\E[32;40mBuild complete. Please reboot.\E[0m"
echo -e "\E[32;40m------------------------------\E[0m"
exit
