# pilomarovation5.py
# CLASS for handling and rendering aurora ovation data from NOAA.

import numpy as np
from pathlib import Path
import requests # To handle json response for seeing conditions from online services.
import json
from datetime import datetime, timedelta

class pilomarovation():
    
    def __init__(self,obs_lat_deg=0,obs_lon_deg=0,width=256,height=128,shell_height_m=110e3,cache_seconds=1800):
        """
        handler for NOAA aurora ovation data.
        
        Imports data from the NOAA website.
        Creates a 'view' of the resulting aurora intensity from any given location on the Earth's surface.
        The resulting view can be exported in a few formats as required.
        
        The basis of this class was generated by AI.
        
        Parameters ----------------------------------------------------------
            obs_lat_deg (float) : Observer's latitude in degrees.
            obs_lon_deg (float) : Observer's longitude in degrees.
            width (int) : Unit width of output mapping. Often the image width in pixels or characters.
            height (int) : Unit height of output mapping. Often the image height in pixels or characters.
            shell_height_m (int) : How high is the aurora projection above the Earth's surface in metres.
            cache_seconds (int) : How many seconds can NOAA data be cached before refreshing from online.
        
        Usage ---------------------------------------------------------------
        
            # Dump view as CSV file.
            from pilomarovation import pilomarovation
            pa = pilomarovation(obs_lat_deg=53.68,obs_lon_deg=-93.40,width=256,height=128,shell_height_m=110e3) # Creat instance.
            pa.create_matrix_csv(filename='matrix.txt') # Write observer's view as text file matrix (csv)

            # Display view inline on the terminal.
            from pilomarovation import pilomarovation
            from textcolor import colordisplay
            pixel_width = 256
            pixel_height = 128
            char_width = int(pixel_width / 2)
            char_height = int(pixel_height / 4)
            pa = pilomarovation(obs_lat_deg=53.0,obs_lon_deg=10.5,width=pixel_width,height=pixel_height,shell_height_m=110e3) # Creat instance.
            pa.create_matrix_csv(filename='matrix.txt') # Write observer's view as text file matrix (csv)
            pa.create_ovation_csv(filename='ovation.txt') # Write ovation data (csv)
            pixellist = pa.get_matrix_list(above=True,below=True) 
            cd = colordisplay(rows=char_height,columns=char_width,name='ovation',fg=15,bg=0)
            cd.ListToBraillePlot(input_list=pixellist,threshold=0,fg=2,bg=0)
            cd.InlineDisplay()
        
        """
        self.AuroraURL = 'https://services.swpc.noaa.gov/json/ovation_aurora_latest.json' # Template for request URL.
        self.AuroraJSON = 'ovation_aurora_latest.json' # Filename on disc.
        self.RequestHeader = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"} # Websites often require headers submitting otherwise the request is denied.
        self.Online = True # Set to False if no web connection available.
        self.CacheMaxSeconds = cache_seconds # How many seconds old can the cache be? After that it needs refreshing.
        self.OutputWidth = width # 360 degree horizontal view is divided into this many points.
        self.OutputHeight = height # 180 degree vertical view is divided into this many points.
        self.IntensityDictionary = {} # Optimised dictionary of the intensity at each point in the shell.
        self.RawDictionary = {} # Raw JSON data from web.
        self.ShellHeight = shell_height_m # Height of shell above Earth surface (metres)
        self.ObserversLatDegree = obs_lat_deg
        self.ObserversLonDegree = obs_lon_deg
        self.ObserversLatRadians = np.radians(obs_lat_deg)
        self.ObserversLonRadians = np.radians(obs_lon_deg)
        self.AzGridRadians = None
        self.AltGridRadians = None
        self.OutputCellLat = None
        self.OutputCellLon = None
        self.AzDivisions = np.linspace(0, 360, self.OutputWidth, endpoint=False) # Create list of 'width' points from 0 to just under 360 evenly spaced.
        self.AltDivisions = np.linspace(-90, 90, self.OutputHeight) # Create list of 'height' points from -90 to 90 evenly spaced.
        self.DataTimestamp = None
        self.refresh() # Refresh data.

    def enu_to_ecef(self, e, n, u, lat0, lon0, h0):
        """
        Convert local ENU coordinates (e, n, u) to ECEF (x, y, z)
        relative to reference point (lat0, lon0, h0) (Observer).
        """
        # WGS84 constants
        a = 6378137.0
        e2 = 6.69437999014e-3

        # Convert reference point to radians
        lat0 = np.radians(lat0)
        lon0 = np.radians(lon0)

        # Compute prime vertical radius of curvature
        N0 = a / np.sqrt(1 - e2 * np.sin(lat0)**2)

        # Reference point in ECEF
        x0 = (N0 + h0) * np.cos(lat0) * np.cos(lon0)
        y0 = (N0 + h0) * np.cos(lat0) * np.sin(lon0)
        z0 = (N0 * (1 - e2) + h0) * np.sin(lat0)

        # Rotation matrix from ENU to ECEF (transpose of ECEF→ENU)
        R = np.array([
            [-np.sin(lon0), -np.sin(lat0)*np.cos(lon0),  np.cos(lat0)*np.cos(lon0)],
            [ np.cos(lon0), -np.sin(lat0)*np.sin(lon0),  np.cos(lat0)*np.sin(lon0)],
            [           0,  np.cos(lat0),               np.sin(lat0)]
        ])

        # Apply rotation
        dx, dy, dz = R @ np.array([e, n, u])

        return x0 + dx, y0 + dy, z0 + dz

    def ecef_to_enu(self, x, y, z, lat0, lon0, h0):
        """
        Convert ECEF coordinates (x, y, z) to local ENU coordinates
        relative to a reference point (lat0, lon0, h0) (Observer).
        All angles in degrees, all distances in meters.
        """
        # WGS84 constants
        a = 6378137.0
        e2 = 6.69437999014e-3

        # Convert reference point to radians
        lat0 = np.radians(lat0)
        lon0 = np.radians(lon0)

        # Compute prime vertical radius of curvature
        N0 = a / np.sqrt(1 - e2 * np.sin(lat0)**2)

        # Reference point in ECEF
        x0 = (N0 + h0) * np.cos(lat0) * np.cos(lon0)
        y0 = (N0 + h0) * np.cos(lat0) * np.sin(lon0)
        z0 = (N0 * (1 - e2) + h0) * np.sin(lat0)

        # Vector from reference to point
        dx = x - x0
        dy = y - y0
        dz = z - z0

        # Rotation matrix from ECEF to ENU
        R = np.array([
            [-np.sin(lon0),              np.cos(lon0),               0],
            [-np.sin(lat0)*np.cos(lon0), -np.sin(lat0)*np.sin(lon0), np.cos(lat0)],
            [ np.cos(lat0)*np.cos(lon0),  np.cos(lat0)*np.sin(lon0), np.sin(lat0)]
        ])

        # Apply rotation
        enu = R @ np.array([dx, dy, dz])
        return enu[0], enu[1], enu[2]

    def latlon_to_ecef(self,lat, lon, r):
        """
        Observer position in EARTH CENTRED, EARTH FIXED reference.
        ECEF is a Cartesian coordinate system with three perpendicular axes:
        Origin: the center of mass of the Earth
        X axis: points toward 0° longitude (intersection of equator and Greenwich meridian)
        Y axis: points toward 90°E longitude (equator, east of Greenwich)
        Z axis: points toward the North Pole
        So an ECEF position is simply: (x,y,z)    

        Parameters ------------------------------------------------
        lat (float) : Observer's latitude in radians.
        lon (float) : Observer's longitude in radians.
        r (float) : Radius of the Earth.
        
        Returns ---------------------------------------------------        
        numpy array : [x,y,z] position in cartesian space.
        """
        x = r * np.cos(lat) * np.cos(lon)
        y = r * np.cos(lat) * np.sin(lon)
        z = r * np.sin(lat)
        return np.array([x, y, z])

    def altaz_array_to_aurora_latlon(self):
        """
        Vectorized conversion of arrays of alt/az values into
        geographic lat/lon on the auroral shell.

        alt_deg_array and az_deg_array must be NumPy arrays
        of the same shape (e.g., 512x1024).

        Parameters -----------------------------------------------

        Returns --------------------------------------------------
        lat (array of float) : List of aurora shell latitudes for each observer altitude angle.
        lon (array of float) : List of aurora shell longitudes for each observer azimuth angle.

        """

        # ---------------------------------------------------------
        # 1. Constants
        # ---------------------------------------------------------
        R_EARTH = 6371e3
        R_SHELL = R_EARTH + self.ShellHeight

        # ---------------------------------------------------------
        # 2. Observer position in ECEF
        # ---------------------------------------------------------
        O = self.latlon_to_ecef(self.ObserversLatRadians, self.ObserversLonRadians, R_EARTH)  # shape (3,)

        # ---------------------------------------------------------
        # 3. ENU basis vectors (ECEF components)
        # ---------------------------------------------------------
        slat, clat = np.sin(self.ObserversLatRadians), np.cos(self.ObserversLatRadians)
        slon, clon = np.sin(self.ObserversLonRadians), np.cos(self.ObserversLonRadians)

        E_hat = np.array([-slon,  clon, 0.0])
        N_hat = np.array([-slat*clon, -slat*slon, clat])
        U_hat = np.array([ clat*clon,  clat*slon, slat])

        # ---------------------------------------------------------
        # 4. Convert alt/az arrays → ENU direction components
        # ---------------------------------------------------------
        ca, sa = np.cos(self.AltGridRadians), np.sin(self.AltGridRadians)
        caz, saz = np.cos(self.AzGridRadians), np.sin(self.AzGridRadians)

        # az measured from North toward East
        # ENU = EAST, NORTH, UP.
        e = ca * saz
        n = ca * caz
        u = sa

        # ---------------------------------------------------------
        # 5. Convert ENU → ECEF for all rays
        # ---------------------------------------------------------
        # d has shape (..., 3)
        d = (
            e[..., None] * E_hat +
            n[..., None] * N_hat +
            u[..., None] * U_hat
        )

        # Normalize all direction vectors
        d /= np.linalg.norm(d, axis=-1, keepdims=True)

        # ---------------------------------------------------------
        # 6. Ray–sphere intersection (vectorized)
        # ---------------------------------------------------------
        # Per-ray dot product O·d: broadcast O over all pixels
        Odotd = np.sum(O * d, axis=-1)      # shape (...,)
        O2 = np.dot(O, O)

        a = 1.0
        b = 2.0 * Odotd
        c = O2 - R_SHELL**2

        disc = b*b - 4*a*c
        mask = disc < 0  # rays that miss the shell

        sqrt_disc = np.sqrt(np.maximum(disc, 0.0))

        t1 = (-b - sqrt_disc) / 2.0
        t2 = (-b + sqrt_disc) / 2.0

        # Choose the positive intersection
        t = np.where(t1 > 0, t1, t2)
        t = np.where(t > 0, t, np.nan)  # mark invalid rays

        # Intersection points in ECEF, shape (..., 3)
        P = O + d * t[..., None]

        # ---------------------------------------------------------
        # 7. Convert intersection → lat/lon
        # ---------------------------------------------------------
        x, y, z = P[..., 0], P[..., 1], P[..., 2]
        r = np.sqrt(x*x + y*y + z*z)

        lat = np.degrees(np.arcsin(z / r))
        lon = np.degrees(np.arctan2(y, x))

        # Mask invalid rays
        lat[mask] = np.nan
        lon[mask] = np.nan

        # Height is inverted, so flip the arrays
        lat = np.flipud(lat)
        lon = np.flipud(lon)
        
        lon = lon % 360 # Convert from -179<>179 to 0<>359 range.
        
        self.OutputCellLat = lat
        self.OutputCellLon = lon

        return True

    def build_grid(self):
        """ 
        Construct a couple of arrays in the dimensions of the output data giving the observer's azimuth and altitude that each 
        output cell represents. These are used to map to the correct cells in the aurora intensity data that is 
        projected into the shell above the observer. 
        
        Parameters -------------------------------------
        
        Returns ----------------------------------------
        az_grid is a repeating list of all azimuth positions. Each row contains all positions, as many rows as alt containts.
        alt_grid is a matching matrix of altitude positions. Each row represents a single alt value, but repeated for all az positions.
        
        """
        # Build a grid of alt/az values
        # self.AzDivisions = np.linspace(0, 360, self.OutputWidth, endpoint=False) # Create list of 'width' points from 0 to just under 360 evenly spaced.
        # self.AltDivisions = np.linspace(-90, 90, self.OutputHeight) # Create list of 'height' points from -90 to 90 evenly spaced.

        az_grid, alt_grid = np.meshgrid(self.AzDivisions, self.AltDivisions) # Create a matrices of all the point combinations.
        # az_grid is a repeating list of all azimuth positions. Each row contains all positions, as many rows as alt containts.
        # alt_grid is a matching matrix of altitude positions. Each row represents a single alt value, but repeated for all az positions.
        
        self.AzGridRadians = np.radians(az_grid)
        self.AltGridRadians = np.radians(alt_grid)
        
        return True
        
    def get_shell_map(self,flip=False):
        """
        Return a list of output cells and the corresponding lat/lon coordinates in the aurora shell.
        List is a list of rows, each row is a list of columns, each entry is a tuple of (lat/lon) on the aurora shell.
        """
        result = []
        for direction_alt in range(self.OutputHeight): # What direction (altitude) are we looking at?
            line = []
            for direction_az in range(self.OutputWidth): # What direction (azimuth) are we looking at?
                shell_lat = int(self.OutputCellLat[direction_alt,direction_az]) # What latitude in the 'shell' are we looking at?
                shell_lon = int(self.OutputCellLon[direction_alt,direction_az]) # What longitude in the 'shell' are we looking at?
                # What's the 'shell' intensity at that point?
                location = (int(shell_lat),int(shell_lon)) # Construct key to dictionary to retrieve intensity at that point. (lat,lon)
                line.append(location)
            result.append(line)
        if flip: result.reverse() # Invert rows
        return result

    def cache_needs_updating(self):
        """ 
        Return False if disc cache can be used. 
        Return True if it needs refreshing from the web. 
        """
        download = self.Online # Set to TRUE to download a fresh copy of the data, FALSE if you can use the disc cache.
        path = Path(self.AuroraJSON) # This is where the disc cache file should be.
        if path.is_file(): # File exists.
            creation_time = datetime.fromtimestamp(path.stat().st_ctime)
            temp = (datetime.now() - creation_time).total_seconds()
            #print("pilomarovation():",self.AuroraJSON,"is",temp,"seconds old.")
            if temp < self.CacheMaxSeconds: # File is young enough.
                download = False # Don't need an online refresh.
        return download
        
    def construct_intensity_dictionary(self):
        """
        Optimise intensity dictionary.
        Takes the raw JSON data received from the web service.
        Creates an indexable dictionary for each lat/lon square with the aurora intensity at that point.
        """
        self.IntensityDictionary = {}
        for ilon,ilat,intensity in self.RawDictionary['coordinates']:
            location = (int(ilat),int(ilon)) # (lat,lon)
            intensity = int(intensity)
            self.IntensityDictionary[location] = intensity
        return True

    def get_matrix_list(self,flip=False,above=True,below=True,pan_angle=0):
        """
        Generate a list of the output file.
        Nested list.
        entries are indexed as list[row][col]
        
        Parameters ---------------------------------------------
        flip (bool) : When TRUE the vertical axis is reversed, rows are listed in reverse order.
        above (bool) : When TRUE intensity above horizon is included, else zero.
        below (bool) : When TRUE intensity below horizon is included, else zero.
        pan_angle (int) : Offset the output matrix by this angle.
        """
        result = []
        for row,output_row in enumerate(range(self.OutputHeight)): # What direction (altitude) are we looking at?
            line = []
            horizon_angle = self.AltDivisions[row] # Is this row ABOVE (+ve) or BELOW (-ve) the observer's horizon?
            #print("row:",row,"horizon_angle",horizon_angle,above,below)
            for output_col in range(self.OutputWidth): # What direction (azimuth) are we looking at?
                if horizon_angle < 0 and below == False: 
                    #print("blocking below horizon")
                    intensity = -99 # Don't show values below horizon.
                elif horizon_angle >= 0 and above == False: 
                    #print("blocking above horizon")
                    intensity = -99 # Don't show values above horizon.
                else:
                    shell_lat = int(self.OutputCellLat[output_row,output_col]) # What latitude in the 'shell' are we looking at?
                    shell_lon = int(self.OutputCellLon[output_row,output_col]) # What longitude in the 'shell' are we looking at?
                    # What's the 'shell' intensity at that point?
                    location = (int(shell_lat),int(shell_lon)) # Construct key to dictionary to retrieve intensity at that point. (lat,lon)
                    intensity = self.IntensityDictionary.get(location,0)
                line.append(int(intensity))
            #print(line)
            result.append(line)
        if flip: result.reverse() # Invert rows
        if pan_angle != 0:
            for i,line in enumerate(result):
                line_len = len(line)
                element_angle = 360.0 / line_len # What angle does each column represent?
                pan_element = int(round(pan_angle / element_angle,0)) # Which cell entry are we looking at?
                result[i] = line[pan_element:] + line[:pan_element]
                #print("Pan: angle=",pan_angle,"len=",line_len,"ele_angle=",element_angle,"pan_ele=",pan_element)
        return result

    def get_ovation_list(self,flip=False,above=True,below=True):
        """
        Export current ovation data as a list.        
        Returns a list of latitudes starting at -90Deg and continuing up to 90Deg
        Each entry in the list is the intensity at 1deg instances starting at longitude 0 (as a list)
        """
        result = []
        for lat in range(-90,91):
            line = []
            for lon in range(0,360):
                line.append(self.IntensityDictionary[(lat,lon)])
            result.append(line)
        if flip: result.reverse() # Invert list so it starts at +90 latitude and counts down.
        return result
        
    def create_ovation_csv(self,filename='ovation.txt',flip=False):
        """
        Dump the raw ovation data as a CSV file. Includes column and row headers.
        """
        if flip: # Invert latitude lines. Start at South Pole and move North.
            start_lat = -90
            end_lat = 91
            step_lat = 1
        else: # Start at North Pol and move South.
            start_lat = 90
            end_lat = -91
            step_lat = -1
        with open(filename,'w') as f: # Create the ovation file.
            # Create column headers
            f.write("\tLon\n")
            line = 'row\t'
            for i in range(0,360):
                line += str(i) + "\t"
            line += "\n"
            f.write(line)
            for lat in range(start_lat,end_lat,step_lat):
                f.write(str(lat) + "\t")
                for lon in range(0,360):
                    f.write(str(self.IntensityDictionary[(lat,lon)]) + "\t")
                f.write("\n")
                    
    def create_matrix_csv(self,filename='matrix.txt',flip=False):
        """
        Writes a disc CSV file of the output matrix. Includes column and row headers.
        """
        # What sequence are we handling the rows?
        if flip: # Flip the rows in reverse order (descending row number).
            start_row = self.OutputHeight - 1
            end_row = -1
            row_step = -1
        else: # Keep rows in ascending row number.
            start_row = 0
            end_row = self.OutputHeight
            row_step = 1
            
        with open(filename,'w') as f: # Create the matrix.
            
            # Create column headers
            line = "row\talt\t"
            for bearing in self.AzDivisions:
                line += str(bearing) + "\t"
            line += "\n"
            f.write(line)

            for i,direction_alt in enumerate(range(start_row,end_row,row_step)): # What direction (altitude) are we looking at?
                f.write(str(direction_alt) + "\t") # row
                f.write(str(self.AltDivisions[i]) + "\t") # Angle
                for direction_az in range(self.OutputWidth): # What direction (azimuth) are we looking at?
                    shell_lat = int(self.OutputCellLat[direction_alt,direction_az]) # What latitude in the 'shell' are we looking at?
                    shell_lon = int(self.OutputCellLon[direction_alt,direction_az]) # What longitude in the 'shell' are we looking at?
                    # What's the 'shell' intensity at that point?
                    location = (int(shell_lat),int(shell_lon)) # Construct key to dictionary to retrieve intensity at that point. (lat,lon)
                    if location in self.IntensityDictionary:
                        intensity = self.IntensityDictionary[location]
                    else:
                        print("Location",location,"not in IntensityDictionary!")
                        intensity = 0
                    f.write(str(int(intensity)) + "\t")
                f.write("\n") # End line.

    def create_matrix_jpg(self,filename,flip=False):
        pass
        
    def get_raw_data(self):
        """
        get_raw_data from web or cache.
        """
        self.RawDictionary = {}
        if self.cache_needs_updating():
            success = False 
            try:
                response = requests.get(self.AuroraURL,headers=self.RequestHeader) # Try to retrieve the response from the remote server.
                response.raise_for_status() # Check for errors in the request.
                self.RawDictionary = response.json() # Convert the response into a dictionary. 
                with open(self.AuroraJSON, "w") as f:
                    f.write(json.dumps(self.RawDictionary, indent=4))
                success = True
            except Exception as e:
                print(e) # Trap all the exception information in the main log file.
                raise Exception("pilomaraurora.GetJSON() failed") from e # Continue with regular exception handling.
        else:
            success = False
            try:
                with open(self.AuroraJSON, "r") as f:
                    self.RawDictionary = json.load(f)
            except Exception as e:
                print(e) # Trap all the exception information in the main log file.
                raise Exception("pilomaraurora.readingJSONcache() failed") from e # Continue with regular exception handling.
            success = True
        if success: self.DataTimestamp = self.RawDictionary.get('Observation Time',str(datetime.now()))
        return success                

    def refresh(self):
        """
        Self contained set of calls to update the data and calculate output results.
        Actual output depends upon the format you require.
        """
        self.get_raw_data() # Get latest Aurora Ovation data from NOAA service or cache.
        self.construct_intensity_dictionary() # Optimise intensity dictionary.
        self.build_grid() # Construct grids of all alt/az viewing directions for output results.
        self.altaz_array_to_aurora_latlon() # Calculate shell locations for each output cell.
        
    def describe_data(self):
        """
        For development. Describe key attributes. 
        """
        print("pilomaraurora.describe_data():")
        print("IntensityDictionary",type(self.IntensityDictionary))
        print("RawDictionary",type(self.RawDictionary))
        print("AzGridRadians",type(self.AzGridRadians),
              "shape:",self.AzGridRadians.shape,
              "example [0,0]:",self.AzGridRadians[0,0],
              "min:",self.AzGridRadians.min(),
              "max:",self.AzGridRadians.max())
        print("AltGridRadians",type(self.AltGridRadians),
              "shape:",self.AltGridRadians.shape,
              "example [0,0]:",self.AltGridRadians[0,0],
              "min:",self.AltGridRadians.min(),
              "max:",self.AltGridRadians.max())
        print("OutputCellLat",type(self.OutputCellLat),
              "shape:",self.OutputCellLat.shape,
              "example [0,0]:",self.OutputCellLat[0,0],
              "min:",self.OutputCellLat.min(),
              "max:",self.OutputCellLat.max())
        print("OutputCellLon",type(self.OutputCellLon),
              "shape:",self.OutputCellLon.shape,
              "example [0,0]:",self.OutputCellLon[0,0],
              "min:",self.OutputCellLon.min(),
              "max:",self.OutputCellLon.max())

class ovationdashboard():
    """
    Simple example terminal interface for aurora ovation data.
    """

    def __init__(self):
        from textcolor import colordisplay, keyboardscanner, textcolor
        #import time
        self.ParameterFileName = '/home/pi/pilomar/data/pilomar_params.json'
        self.pixel_width = 256
        self.pixel_height = 128
        self.char_width = int(self.pixel_width / 2)
        self.char_height = int(self.pixel_height / 4)
        self.obs_lat_deg = 0
        self.obs_lon_deg = 0
        self.shell_height_m=110e3
        self.RefreshSeconds = 15*60 # Refresh every 15 minutes.        
        self.pan_deg = 180 # Start out facing NORTH.
        self.probability = 0 # 50% chance of seeing Aurora.
        self.icd = colordisplay(rows=self.char_height + 10,columns=self.char_width + 6,row=1,col=1,name='interactive_ovation',fg=15,bg=0)
        self.icd.DrawBorder = True # Draw border around window.
        self.icd.SetBorderColors(textcolor.GREEN,textcolor.BLACK) # Set border colors.
        self.icd.ClipWindow = True # Clip the display if the terminal area is insufficient. This means we see at least something.
        self.icd.PlaceString(' +90[X]',row=1,col=0)
        self.icd.PlaceString(' ',      row=2,col=0)
        self.icd.PlaceString(' ',      row=3,col=0)
        self.icd.PlaceString(' ',      row=4,col=0)
        self.icd.PlaceString(' ',      row=5,col=0)
        self.icd.PlaceString(' ',      row=6,col=0)
        self.icd.PlaceString(' ',      row=7,col=0)
        self.icd.PlaceString(' ',      row=8,col=0)
        self.icd.PlaceString(' ',      row=9,col=0)
        self.icd.PlaceString(' ',      row=10,col=0)
        self.icd.PlaceString(' ',      row=11,col=0)
        self.icd.PlaceString(' ',      row=12,col=0)
        self.icd.PlaceString(' ',      row=13,col=0)
        self.icd.PlaceString(' ',      row=14,col=0)
        self.icd.PlaceString(' ',      row=15,col=0)
        self.icd.PlaceString('  +0',   row=16,col=0)
        self.icd.PlaceString(' ',      row=17,col=0)
        self.icd.PlaceString(' ',      row=18,col=0)
        self.icd.PlaceString(' ',      row=19,col=0)
        self.icd.PlaceString(' ',      row=20,col=0)
        self.icd.PlaceString(' ',      row=21,col=0)
        self.icd.PlaceString(' ',      row=22,col=0)
        self.icd.PlaceString(' ',      row=23,col=0)
        self.icd.PlaceString(' ',      row=24,col=0)
        self.icd.PlaceString(' ',      row=25,col=0)
        self.icd.PlaceString(' ',      row=26,col=0)
        self.icd.PlaceString(' ',      row=27,col=0)
        self.icd.PlaceString(' ',      row=28,col=0)
        self.icd.PlaceString(' ',      row=29,col=0)
        self.icd.PlaceString(' ',      row=30,col=0)
        self.icd.PlaceString(' ',      row=31,col=0)
        self.icd.PlaceString(' -90',   row=32,col=0)
        centre_col = int(self.char_width / 2) + 4
        
        self.icd.PlaceString('[AZIMUTH]',                        row=33,col=centre_col - 3)
        self.icd.PlaceString('Observer:  Lat: [OBSLAT]deg',      row=35,col=4)
        self.icd.PlaceString('           Lon: [OBSLON]deg',      row=36,col=4)
        self.icd.PlaceString('  Aurora:  Alt: [AURALT]km',       row=37,col=4)
        self.icd.PlaceString('           Probability: >[AURPRB]',row=38,col=4)
        self.icd.PlaceString('Choose key',row=40,col=4)

        self.icd.PlaceString('8,w = Move North    2,z = Move South',row=35,col=44)
        self.icd.PlaceString('a,4 = Move West     s,6 = Move East', row=36,col=44)
        self.icd.PlaceString('  1 = Higher          0 = Lower',     row=37,col=44)
        self.icd.PlaceString('  . = Lower           3 = Higher',    row=38,col=44)
        self.icd.PlaceString('  r = Refresh         x = Exit',      row=39,col=44)
        
        self.icd.PlaceString('Updated: [UPDATEDT               ]',row=35,col=87)
        self.icd.PlaceString('Refresh: [REFRESHHMS]',             row=36,col=87)
        self.icd.PlaceString('   Data: [DATADT                 ]',row=37,col=87)
        self.icd.ScanForFields() # Scan the current image for field markers.
        self.icd.FieldFormat('OBSLAT',justify='r')
        self.icd.FieldFormat('OBSLON',justify='r')
        self.icd.FieldFormat('AURALT',justify='r')
        self.icd.FieldFormat('AURPRB',justify='r')
        self.icd.FieldFormat('AZIMUTH',justify='c')
        horizon_row = int(self.char_height / 2)
        startrow, startcol = self.icd.FieldLocation("X") # Get location of the anchor field for the chart.
        line = " " * self.char_width
        for row in range(horizon_row + startrow):
            self.icd.PlaceString(line,row=row,col=startcol,bg=textcolor.NAVY)
        for row in range(horizon_row + startrow,self.char_height + startrow):
            self.icd.PlaceString(line,row=row,col=startcol,bg=textcolor.DARKRED)
        self.keyboard = keyboardscanner()
        self.RefreshTimestamp = None
        self.establish_location()
        
    def establish_location(self):
        """
        If startup parameters specify location (lat/lon) use that.
        Else if parameter file exists, use that.
        Else default to 0,0
        """
        import sys
        import os
        run_args = sys.argv[1:] # Ignore 1st argument which is this program name.
        for i in run_args:
            if i.startswith('?') or i.startswith('h'): # Help
                print(textcolor.yellow("HELP"))
                print(" paramfile={pilomar parameterfile name}")
                print(" lat={latitude degrees}")
                print(" lon={longitude degrees}")
                exit()
            if i.startswith('paramfile='): # Specify parameter filename to use.
                # Alternative parameter files are useful for test/dev/debug and also for
                # supporting alternative configurations.
                self.ParameterFileName = i.split('=')[1]
                print(textcolor.orange("Startup parameter file is:",self.ParameterFileName))
            elif i.startswith('lat='):
                self.obs_lat_deg = float(i.split("=")[1])
            elif i.startswith('lon='):
                self.obs_lon_deg = float(i.split("=")[1])
            else: print (textcolor.red('Ignored startup parameter "' + str(i) + '"'))
        if self.ParameterFileName != None: # If Pilomar parameter file exists, use that.
            if os.path.exists(self.ParameterFileName):
                with open(self.ParameterFileName,'r') as f:
                    param_dict = json.load(f)
                # Extract latitude degrees from parameter list.
                home_lat_str = param_dict.get('HomeLat','0.0 N')
                self.obs_lat_deg = float(home_lat_str.split(" ")[0]) # Convert to float value.
                if home_lat_str.split(" ")[1] == "S": self.obs_lat_deg = self.obs_lat_deg * -1 # -ve for southern hemisphere in Skyfield.
                # Extract longitude degrees from parameter list.
                home_lon_str = param_dict.get('HomeLon','0.0 E')
                self.obs_lon_deg = float(home_lon_str.split(" ")[0]) # Convert to float value.
                if home_lon_str.split(" ")[1] == "W": self.obs_lon_deg = self.obs_lon_deg * -1 # -ve for southern hemisphere in Skyfield.
                print("From",self.ParameterFileName,"lat/lon",self.obs_lat_deg,self.obs_lon_deg)

    def Display(self):
        pa = pilomarovation(obs_lat_deg=self.obs_lat_deg,
                            obs_lon_deg=self.obs_lon_deg,
                            width=self.pixel_width,
                            height=self.pixel_height,
                            shell_height_m=self.shell_height_m) # Creat instance.
        pixellist = pa.get_matrix_list(above=True,below=True,pan_angle=self.pan_deg) 
        self.RefreshTimestamp = datetime.now()
        self.icd.ListToBraillePlot(input_list=pixellist,threshold=self.probability,fg=textcolor.LIGHTGREEN,bg=None,fieldname="X")
        temp_lon = self.obs_lon_deg
        if temp_lon > 180: temp_lon = self.obs_lon_deg - 360
        if self.obs_lat_deg >= 0: view_direction = "NORTH"
        else: view_direction = "SOUTH"
        self.icd.FieldValue("AZIMUTH",view_direction)
        self.icd.FieldValue("OBSLAT",int(self.obs_lat_deg))
        self.icd.FieldValue("OBSLON",int(self.obs_lon_deg))
        self.icd.FieldValue("AURALT",int(self.shell_height_m / 1000))
        self.icd.FieldValue("AURPRB",str(self.probability) + "%")
        self.icd.FieldValue("UPDATEDT",str(self.RefreshTimestamp).split(".")[0])
        temp = self.RefreshTimestamp + timedelta(seconds=self.RefreshSeconds)
        temp = str(temp).split(' ')[1].split('.')[0]
        self.icd.FieldValue("REFRESHHMS",temp)
        temp = str(pa.DataTimestamp).split('.')[0]
        self.icd.FieldValue("DATADT",temp)
        self.icd.Display()
        
    def io_loop(self):
        while True:
            keypress = self.keyboard.Check().lower()
            if keypress != "":
                if keypress in ["a"]: self.obs_lon_deg -= 10.0 # observer moves West 10 degrees
                elif keypress in ["4"]: self.obs_lon_deg -= 1.0 # observer moves West 1 degree
                elif keypress in ["s"]: self.obs_lon_deg += 10.0 # observer moves East 10 degrees
                elif keypress in ["6"]: self.obs_lon_deg += 1.0 # observer moves East 1 degrees
                elif keypress in ["w"]: self.obs_lat_deg += 10.0 # Observer moves North 10 degrees
                elif keypress in ["8"]: self.obs_lat_deg += 1.0 # Observer moves North 1 degree
                elif keypress in ["z"]: self.obs_lat_deg -= 10.0 # Observer moves South 10 degrees
                elif keypress in ["2"]: self.obs_lat_deg -= 1.0 # Observer moves South 1 degree
                elif keypress in ["1"]: self.shell_height_m += 10e3 # Aurora increases altitude 10km
                elif keypress in ["0"]: self.shell_height_m -= 10e3 # Aurora decreases altitude 10km
                elif keypress in ["."]: self.probability -= 5 # Decrease probability threshold
                elif keypress in ["3"]: self.probability += 5 # Increase probability threshold
                elif keypress in ["r"]: self.Display() # Refresh the display immediately.
                elif keypress in ["x"]: break
                else: continue

                self.obs_lat_deg = min(self.obs_lat_deg,90)
                self.obs_lat_deg = max(self.obs_lat_deg,-90)
                self.obs_lon_deg = self.obs_lon_deg % 360
                self.shell_height_m = max(40e3,self.shell_height_m)
                self.probability = max(0,self.probability)
                self.probability = min(100,self.probability)
                self.pan_deg = self.pan_deg % 360
                if self.obs_lat_deg >= 0: self.pan_deg = 180 # Put NORTH in the centre of the chart.
                else: self.pan_deg = 0 # Put SOUTH in the centre of the chart.
                
                self.Display() # Update display
            elif (datetime.now() - self.RefreshTimestamp).total_seconds() > self.RefreshSeconds: # Refresh every 15 minutes.
                self.Display()
            time.sleep(0.25)
        
if __name__ == "__main__":
    from textcolor import textcolor
    import time
    od = ovationdashboard() # Create terminal interface for the ovation data.
    print(textcolor.clearall()) # Wipe the display clean.
    od.Display() # Initial display.
    od.io_loop() # Loop through updates and user input.
